### ISSUE TITLE
transactions endpoint started to return weird results 

### ISSUE THREAD

**Issue by RoSonic** [ElrondNetwork/api.elrond.com#662] opened 2022-06-03 06:34 UTC
The transactions endpoint started to return weird results (since yesterday)

As example for https://api.elrond.com/transactions?token=SHARK-8c1c46-26

Instead of returning only transactions for identifier = "SHARK-8c1c46-26", it will return all transaction with identifier starting with "SHARK-8c1c46-" and all transactions with identifier ending with "-26", 
ex:  SHARK-8c1c46-9b, SHARK-8c1c46-45, VIP-6b45f0-26, MOTAN-555b35-26, EGGS-1b4aec-26 etc.

**Comment by tanghel** [comment] 2022-06-03 06:54
thank you for reporting this! 🙏 

It was indeed caused by the refactoring in PR https://github.com/ElrondNetwork/api.elrond.com/pull/660
And it was fixed in the PR https://github.com/ElrondNetwork/api.elrond.com/pull/663

**Closed by tanghel** 2022-06-03 06:54 UTC
